version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - CONFIG_FILE=/app/config/config.yaml
    # volumes:
    #   - ./config:/app/config
    restart: on-failure

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=myapp_db
      - POSTGRESQL_USERNAME=myapp_user
      - POSTGRESQL_PASSWORD=your_secure_password
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myapp_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    command: redis-server --requirepass your_redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: