app:
  name: "MyApp"
  version: "1.0.0"
  port: 8080

postgres:
  host: "postgres"
  port: 5432
  user: "myapp_user"
  password: "your_secure_password"
  dbname: "myapp_db"
  migrations:
    enabled: true
    path: "/app/migrations/postgres"

redis:
  address: "redis:6379"
  username:  ""
  password: ""
  db: 0

log:
  level: "debug"
  output: "file"
  file:
    path: "/app/logs/myapp.log"
    max_size: 100
    max_age: 30
    max_backups: 3

cassandra:
  hosts:
    - "cassandra-node1"
  port: 9042
  keyspace: "myapp_keyspace"
  username: "myapp_user"
  password: "your_secure_password"
  consistency: "QUORUM"
  proto_version: 4
  migrations:
    enabled: true
    path: "/app/migrations/cassandra"
  replication:
    strategy: "SimpleStrategy"
    replication_factor: 1


auth:
  jwt_secret: "your_very_secure_jwt_secret"